### ISSUE TITLE
AuthnRequest

### ISSUE THREAD

**Issue by aaronchi** [instructure/ruby-saml2#1]
This is a nice library. Any plans to include the ability to generate a saml request?

**Comment by ccutrer** [comment]
Desires- yes. Plans- no. Unfortunately priorities say that we already have a working solution using the ruby-saml gem for being an SP, so can't devote the resources to doing it cleaner with this gem. If/when our customers demand a better experience with the SP (automatically pulling in the IdP's metadata, for example), we'll be able to add all of that to this gem.

If you're willing to do the work of serializing an AuthnRequest with this library, your pull request would definitely be reviewed. This gem was designed to use the same objects for both SP and IdP by modeling as close to the SAML schemas as possible, so it shouldn't be tooooo much work to make sure you can build up a full AuthnRequest in Ruby, and then serialize it to XML.

**Comment by ccutrer** [comment]
This has been all implemented.
