### ISSUE TITLE
Parsing and responding

### ISSUE THREAD

**Issue by td512** [instructure/ruby-saml2#11]
When calling `HTTPRedirect.decode`, it returns `#<SAML2::AuthnRequest @pretty=true, @errors=[], @id=nil, @issue_instant=nil>`. Subsequently `Response.respond_to` errors on line 24 because it's unable to get the ACS location from the SAML. Any ideas?

**Comment by ccutrer** [comment]
Did you check that your `AuthnRequest` object returns true for `valid_interoperable_profile?`? The `Response.respond_to` method assumes that (though should probably check it), and the profile (https://saml2int.org/profile/current/#section82) requires that `assertion_consumer_service_url` be present in the `AuthnRequest`.

**Comment by td512** [comment]
The SAML request is issued by Google, and when I dump the decoded XML it looks okay. The object returns true on `valid_interoperable_profile?`

**Comment by td512** [comment]
additionally it's now sort of working. acs is now spitting out a string. I suspect that `.location` needs to be removed https://github.com/instructure/ruby-saml2/blob/master/lib/saml2/response.rb#L24

**Comment by td512** [comment]
@ccutrer any ideas?

**Comment by ccutrer** [comment]
can you provide the AuthnRequest raw XML (or base64 encoded)? feel free to redact any sensitive identifiers

**Comment by td512** [comment]
@ccutrer sorry about the delay

```
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="{{Google-SAML-IDENT}}" Version="2.0" IssueInstant="2019-10-24T11:42:53Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" ProviderName="google.com" IsPassive="false" AssertionConsumerServiceURL="https://www.google.com/a/{{Google-Domain}}/acs"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">google.com/a/{{Google-Domain}}</saml:Issuer><samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" /></samlp:AuthnRequest>
```

**Comment by td512** [comment]
@ccutrer any ideas here?

**Comment by ccutrer** [comment]
ah, I see now. `AuthnRequest#assertion_consumer_service` requires that `AuthnRequest#resolve` is called first (passing in the `ServiceProvider` metadata object). `Response#respond_to` therefore also requires that. The example in the readme does this, but the docs for `Response#respond_to` don't call that out. I'm updating the docs.

**Comment by td512** [comment]
@ccutrer one more. What do I need for the service provider object? There are no examples of what a SP config is meant to look like. I've got everything else down though

**Comment by td512** [comment]
@ccutrer new problem. I have the following SP XML:

```
<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
                     validUntil="2019-11-07T21:18:19Z"
                     cacheDuration="PT604800S"
                     entityID="google.com/a/northbridge.xyz">
    <md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
        <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                     Location="https://www.google.com/a/{{domain}}/acs"
                                     index="1" />
        
    </md:SPSSODescriptor>
</md:EntityDescriptor>```

and I'm getting the error: `NoMethodError (undefined method `assertion_consumer_services' for nil:NilClass)` when using `authn_request.resolve(self.class.service_provider)`

**Comment by ccutrer** [comment]
it appears whatever `self.class.service_provider` is, is returning `nil`. I'm having no problem with your XML:

```
xml = '<copy/paste from above>'
entity = SAML2::Entity.parse(xml)
=> #<SAML2::Entity @contacts=nil, @entity_id=nil, @roles=nil, @id=nil>
entity.service_providers.first.assertion_consumer_services
=> [#<SAML2::Endpoint::Indexed @is_default=nil, @location="https://www.google.com/a/{{domain}}/acs", @binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST", @index=1>]
```

**Comment by td512** [comment]
Weird. I think I've got it, however...

It looks like the parser isn't working correctly, the acs url returns as `<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://www.google.com/a/northridge.xyz/acs" index="1"/>` @ccutrer

**Comment by td512** [comment]
Never mind! I think I've got it. was missing a `.location`
