### ISSUE TITLE
gem 'nokogiri-xmlsec-me-harder', '0.9.3pre' not found

### ISSUE THREAD

**Issue by Macpeters** [instructure/ruby-saml2#2]
On the rubygems page for the above gem, the latest version is 0.9.2.  

```  gem install nokogiri-xmlsec-me-harder -v '0.9.3pre'  ``` results in 
_ERROR:  Could not find a valid gem 'nokogiri-xmlsec-me-harder' (= 0.9.3pre) in any repository_

I'm not sure if the gem version used to exist, and was removed, or what happened, but it seems saml2 has a runtime dependancy on a non-existent version.  Unless I'm missing something?

**Comment by ccutrer** [comment]
Correct. SAML2 depends on an unreleased version of the nokogiri-xmlsec-me-harder gem. In your own Gemfile you can add the line `gem 'nokogiri-xmlsec-me-harder', '0.9.3pre', require: false, github: 'instructure/nokogiri-xmlsec-me-harder', ref: '57d071040cc4649db9f158e09bbcea028271a4a6'`, and it should work. Gemspecs are unable to specify a source to find a gem, so we can't do this for you automatically.

**Comment by Macpeters** [comment]
I have that line, but getting ```  An error occurred while installing nokogiri-xmlsec-me-harder (0.9.3pre), and Bundler cannot continue.
Make sure that `gem install nokogiri-xmlsec-me-harder -v '0.9.3pre'` succeeds before bundling. ```

**Comment by ccutrer** [comment]
Do you have xmlsec development libraries installed locally?

**Comment by Macpeters** [comment]
I don't believe so - I'm actually trying to install canvas, which is fairly convoluted, and your gem is a dependency.  ``` xmlsec -v ``` and  ``` nokogiri-xmlsec -v  ``` both give me nothing, though, if that answers your question.
