### ISSUE TITLE
Weird behavior of SAML2::Entity.parse

### ISSUE THREAD

**Issue by phokz** [instructure/ruby-saml2#8]
Hi, I suggest to change README.md as shown here:
https://github.com/phokz/ruby-saml2/commit/0d4f2a9749090fd823f969e46fa22164baf95e54

For some reason, passing Pathname object to SAML2::Entity.parse causes xml file truncation/rewind to beginning to occur.

It works great with spec/fixtures/service_provider.xml, but fails in case where both certificates are
used. In the service_provider.xml first cert is replaced by Base64 encoded string "I use this for encryption".

In rspec spec/lib/service_provider_spec.rb there is a test, but it passes a string to SAML2::Entity.parse, which also works.

**Comment by phokz** [comment]
Hi, we have found the root cause of the failure, and it seems to be in Nokogiri.
Nokogiri accepts either string or whatever responds to 'read' method.
Pathname objects respond to read, but they do not keep state or file opened.
Nokogiri reads input in chunks, calling read(SOME_CHUNK_SIZE) possibly several times, based on file size. Pathname#read allways reads from the beginning of file.

**Comment by phokz** [comment]
Hi, I made a PR in nokogiri repository:
https://github.com/sparklemotion/nokogiri/pull/1821

However, I still think it is good to update the README.md file.

**Comment by ccutrer** [comment]
Yup, I saw the change in your other PR, and it makes sense. Honestly, I think it's a weird way for Pathname to behave. I guess it makes sense to not keep state of the current file position in an object that only represents where the file is, but maybe it shouldn't accept a length argument at all to Pathname#read in that case. Either way, ducktyping fail.
